INSERT INTO yoda_quotes VALUES (1, 'When nine hundred years old you reach, look as good you will not');
INSERT INTO yoda_quotes VALUES (2, 'Truly wonderful, the mind of a child is');
INSERT INTO yoda_quotes VALUES (3, 'Fear is the path to the dark side…fear leads to anger…anger leads to hate…hate leads to suffering');
INSERT INTO yoda_quotes VALUES (4, 'Wars not make one great');
INSERT INTO yoda_quotes VALUES (5, 'Do. Or do not. There is no try');
INSERT INTO yoda_quotes VALUES (6, 'You must unlearn what you have unlearned');
INSERT INTO yoda_quotes VALUES (7, 'Always two there are, no more, no less. A master and an apprentice.');
INSERT INTO yoda_quotes VALUES (8, 'Always pass on what you have learned');
INSERT INTO yoda_quotes VALUES (9, 'You fail because you don’t believe');
INSERT INTO yoda_quotes VALUES (10, 'The dark side clouds everything. Impossible to see the future is');
INSERT INTO yoda_quotes VALUES (11, 'In the end, cowards are those who follow the dark side');
INSERT INTO yoda_quotes VALUES (12, 'Mind what you have learned. Save you it can.');
INSERT INTO yoda_quotes VALUES (13, 'You will find only what you bring in');
INSERT INTO yoda_quotes VALUES (14, 'In a dark place we find ourselves, and a little more knowledge lights our way');
INSERT INTO yoda_quotes VALUES (15, 'A challenge lifelong it is, not to bend fear into anger');
INSERT INTO yoda_quotes VALUES (16, 'Control, control, you must learn control');
INSERT INTO yoda_quotes VALUES (17, 'May the Force be with you');
INSERT INTO yoda_quotes VALUES (18, 'I cannot teach him. The boy has no patience');
INSERT INTO yoda_quotes VALUES (19, 'To be Jedi is to face the truth, and choose. Give off light, or darkness, Padawan. Be a candle or the night.');
INSERT INTO yoda_quotes VALUES (20, 'To a dark place this line of thought will carry us. Great care we must take');
INSERT INTO yoda_quotes VALUES (21, 'A challenge lifelong it is, not to bend fear into anger');
